### PR TITLE
fix: resolve user details save failure and API error handling (#64)

### LINKED ISSUE #64: [Bug] Failed to save user - User Details Page
Route: `users/:userId`

Image

Current Behaviour: 

1. UI show the error : `Failed to save user`
2. API doesn't show an error on API failure, still returns 200 response code

Expected Behaviour: 

1. When user details is edited and clicked on save.
2. User must be saved.
3. Data is updated in the database
4. Data is retained when we return back to the same screen.

- In case of error, API should throw an error as well.

### PR DESCRIPTION
**Pull request by Vivekk0712**
# Pull Request

## Description

This PR fixes the user details save functionality that was failing due to data structure mismatches and improper error handling.

**Issues Fixed:**
- UI showed "Failed to save user" error
- API returned 200 status code even on failures
- User data was not persisted to database
- Changes were lost when navigating back to the user details page

**Root Causes:**
1. Frontend sent `role` as an object `{name: 'admin'}` but backend expected a string
2. Backend service caught errors and returned `null` instead of throwing
3. Backend controller didn't validate the service response
4. Frontend sent `permissions` array that doesn't exist in User model
5. Permissions weren't properly derived from user roles on page load

**Changes Made:**
- Fix data structure mismatch: send role as string instead of object
- Remove silent error handling in user service that returned null
- Add proper error throwing to return correct HTTP status codes
- Filter out permissions field that doesn't exist in User model
- Implement role-based permissions (admin/user roles)
- Add response validation in frontend
- Update permissions to derive from user role on load
- Assign user role when admin is unchecked (instead of null)

Fixes #64

## Type of Change

- [x] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update
- [ ] Refactor
- [ ] Other (please describe):

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

## Screenshots

**Before:** User details page showed "Failed to save user" error with API returning 200 status
Screenshot 2026-01-05 141155

**After:** User details save successfully with proper success message and correct error codes on failure

Screenshot 2026-01-05 143344-imageonline co-merged
Database updation ss

## Additional Context

**Files Modified:**
- `backend/src/user/user.controller.ts` - Added permissions filtering, improved error handling, changed return type from `User | null` to `User`
- `backend/src/user/user.service.ts` - Removed silent error handling (try-catch returning null), now throws errors properly
- `frontend/src/pages/AdminUserDetailPage.tsx` - Fixed data structure, added response validation, implemented role-based permissions loading

**Testing Performed:**
- ✅ User details save successfully
- ✅ Changes persist when navigating away and back
- ✅ Admin role assignment works correctly
- ✅ API returns 500 status code on failure (not 200)
- ✅ Error messages displayed properly to user
- ✅ Database verification via Prisma Studio confirms changes persist

**Note:** Permissions are now role-based. The User model doesn't have a permissions field - permissions are stored in the Role model and derived from the user's assigned role (admin role = all permissions, user role = read only).

### CODE REVIEW

File: frontend/src/pages/AdminUserDetailPage.tsx [hunk 1]
```diff
@@ -29,19 +29,28 @@ export default function AdminUserDetailPage() {
...
           read: false,
           write: false,
           admin: false,
           delete: false,
         };
-        if ((data as any).permissions && Array.isArray((data as any).permissions)) {
-          for (const p of (data as any).permissions) perms[p] = true;
+        
+        // If user has admin role, grant all permissions
+        if (data.role?.name === 'admin') {
```
Comment (akbatra567) [inline frontend/src/pages/AdminUserDetailPage.tsx]: Can you move this logic to a util or helper class ?

**Review by akbatra567 — CHANGES_REQUESTED** [review]

**Review by akbatra567 — APPROVED** [review]
